In [1]:
import numpy as np

In [2]:
def softmax_loss(x, y):
    N = x.shape[0]
    print('logits:\n', x, '\n')
    
    shifted_logits = x - np.max(x, axis=1, keepdims=True)
    print('logits (shifted):\n', shifted_logits, '\n')
    
    Z = np.sum(np.exp(shifted_logits), axis=1, keepdims=True)
    print('Z:\n', Z, '\n')
    
    log_probs = shifted_logits - np.log(Z)
    print('log_probs:\n', log_probs, '\n')
    
    probs = np.exp(log_probs)
    print('probs:\n', probs, '\n')
    
    expected_probs = np.exp(x) / np.sum(np.exp(x), axis=1, keepdims=True)
    print('expected_probs:\n', expected_probs, '\n')
    
    loss = -np.sum(log_probs[np.arange(N), y]) / N
    print('loss:\n', loss, '\n')
    
    return loss

In [3]:
x = np.array([[3, 7, 2], [6, 5, 0]])
y = np.array([2, 1])
softmax_loss(x, y)

logits:
 [[3 7 2]
 [6 5 0]] 

logits (shifted):
 [[-4  0 -5]
 [ 0 -1 -6]] 

Z:
 [[1.02505359]
 [1.37035819]] 

log_probs:
 [[-4.02474489 -0.02474489 -5.02474489]
 [-0.31507216 -1.31507216 -6.31507216]] 

probs:
 [[0.01786798 0.97555875 0.00657326]
 [0.72973621 0.26845495 0.00180884]] 

expected_probs:
 [[0.01786798 0.97555875 0.00657326]
 [0.72973621 0.26845495 0.00180884]] 

loss:
 3.169908525402037 



3.169908525402037