## Call by value

In [1]:
# 1st test
a = 1

def inc_op(x):
    x += 1
    
print(f'a: {a}')
print('inc_op')
inc_op(a)
print(f'a: {a}')

a: 1
inc_op
a: 1


In [2]:
# 2nd test
a = 1

def assign_op(x):
    x = 100
    
print(f'a: {a}')
print('assign_op')
assign_op(a)
print(f'a: {a}')

a: 1
assign_op
a: 1


## Call by reference

In [3]:
# 1st test
a = [1]

def append_op(x):
    x.append(67)
    
print(f'a: {a}')
print('append_op')
append_op(a)
print(f'a: {a}')

a: [1]
append_op
a: [1, 67]


In [4]:
# 2nd test
a = [1]

def assign_list(x):
    x = [7, 7, 7, 8, 8, 9]
    
print(f'a: {a}')
print('assign_list')
assign_list(a)
print(f'a: {a}')

a: [1]
assign_list
a: [1]


In [5]:
# 3rd test for numpy arrays
import numpy as np
a = np.arange(30).reshape(3, 10)

def add_op(a):
    a += 100
    
print(f'a: {a}')
print('add_op')
add_op(a)
print(f'a: {a}')

a: [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
add_op
a: [[100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]]


In [6]:
# 4th test for numpy arrays
a = np.arange(30).reshape(3, 10)

def add_op_for_cols(a):
    a[:, :2] += 900
    
print(f'a: {a}')
print('add_op_for_cols')
add_op_for_cols(a)
print(f'a: {a}')

a: [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
add_op_for_cols
a: [[900 901   2   3   4   5   6   7   8   9]
 [910 911  12  13  14  15  16  17  18  19]
 [920 921  22  23  24  25  26  27  28  29]]


In [7]:
# 5th test for numpy arrays
a = np.arange(30).reshape(3, 10)

def add_op_for_2nd_col(a):
    a[:, 1] += 900
    
print(f'a: {a}')
print('add_op_for_2nd_col')
add_op_for_2nd_col(a)
print(f'a: {a}')

a: [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
add_op_for_2nd_col
a: [[  0 901   2   3   4   5   6   7   8   9]
 [ 10 911  12  13  14  15  16  17  18  19]
 [ 20 921  22  23  24  25  26  27  28  29]]


In [8]:
# 6th test for numpy arrays
a = np.arange(30).reshape(3, 10)

def change_op(a):
    a[:, :3] = 333
    
print(f'a: {a}')
print('change_op')
change_op(a)
print(f'a: {a}')

a: [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
change_op
a: [[333 333 333   3   4   5   6   7   8   9]
 [333 333 333  13  14  15  16  17  18  19]
 [333 333 333  23  24  25  26  27  28  29]]


In [9]:
# 7th test for numpy arrays
a = np.arange(30).reshape(3, 10)

def change_array(a):
    a = np.arange(50)
    
print(f'a: {a}')
print('change_array')
change_array(a)
print(f'a: {a}')

a: [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
change_array
a: [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [10]:
# 8th test for dictionaries
a = {'a': 40, 'b': 55}

def change_dict(a):
    a = {'x': 99}
    
print(f'a: {a}')
print('change_dict')
change_dict(a)
print(f'a: {a}')

a: {'a': 40, 'b': 55}
change_dict
a: {'a': 40, 'b': 55}
