# [XOR swap - a beautiful trick](https://en.wikipedia.org/wiki/XOR_swap_algorithm)

In [1]:
import numpy as np

## Swap 2 integers

In [2]:
a = 123
b = 67
print(a, b)

a ^= b
b ^= a
a ^= b
print(a, b)

123 67
67 123


## Swap 2 booleans

In [3]:
a = True
b = False
print(a, b)

a ^= b
b ^= a
a ^= b
print(a, b)

True False
False True


## Swap 2 numpy arrays

In [4]:
a = np.array([[3, 5, 7], [9, 14, 21]])
b = np.array([[42, 8, 13], [18, 99, 453]])
print('a\n', a)
print('b\n', b)
print()

a ^= b
b ^= a
a ^= b
print('a\n', a)
print('b\n', b)

a
 [[ 3  5  7]
 [ 9 14 21]]
b
 [[ 42   8  13]
 [ 18  99 453]]

a
 [[ 42   8  13]
 [ 18  99 453]]
b
 [[ 3  5  7]
 [ 9 14 21]]


## Swap 2 numpy arrays for a given list of indices

In [5]:
a = np.array([[3, 5, 7], [9, 14, 21], [5, 55, 555]])
b = np.array([[42, 8, 13], [18, 99, 453], [6, 66, 666]])
rows = [0, 2]
print('a\n', a)
print('b\n', b)
print()

a[rows, :] ^= b[rows, :]
b[rows, :] ^= a[rows, :]
a[rows, :] ^= b[rows, :]
print('a\n', a)
print('b\n', b)

a
 [[  3   5   7]
 [  9  14  21]
 [  5  55 555]]
b
 [[ 42   8  13]
 [ 18  99 453]
 [  6  66 666]]

a
 [[ 42   8  13]
 [  9  14  21]
 [  6  66 666]]
b
 [[  3   5   7]
 [ 18  99 453]
 [  5  55 555]]
