# [XOR swap - a beautiful trick](https://en.wikipedia.org/wiki/XOR_swap_algorithm)

In [1]:
import numpy as np

## Swap 2 integers

In [2]:
a = 123
b = 67
print(a, b)

a ^= b
b ^= a
a ^= b
print(a, b)

123 67
67 123


## Swap 2 booleans

In [3]:
a = True
b = False
print(a, b)

a ^= b
b ^= a
a ^= b
print(a, b)

True False
False True


## Swap 2 numpy arrays

In [4]:
a = np.array([[3, 5, 7], [9, 14, 21]])
b = np.array([[42, 8, 13], [18, 99, 453]])
print('a\n', a)
print('b\n', b)
print()

a ^= b
b ^= a
a ^= b
print('a\n', a)
print('b\n', b)

a
 [[ 3  5  7]
 [ 9 14 21]]
b
 [[ 42   8  13]
 [ 18  99 453]]

a
 [[ 42   8  13]
 [ 18  99 453]]
b
 [[ 3  5  7]
 [ 9 14 21]]


## Swap 2 numpy arrays for a given list of indices

In [5]:
a = np.array([[3, 5, 7], [9, 14, 21], [5, 55, 555]])
b = np.array([[42, 8, 13], [18, 99, 453], [6, 66, 666]])
rows = [0, 2]
print('a\n', a)
print('b\n', b)
print()

a[rows, :] ^= b[rows, :]
b[rows, :] ^= a[rows, :]
a[rows, :] ^= b[rows, :]
print('a\n', a)
print('b\n', b)

a
 [[  3   5   7]
 [  9  14  21]
 [  5  55 555]]
b
 [[ 42   8  13]
 [ 18  99 453]
 [  6  66 666]]

a
 [[ 42   8  13]
 [  9  14  21]
 [  6  66 666]]
b
 [[  3   5   7]
 [ 18  99 453]
 [  5  55 555]]


## XOR swap function

In [6]:
def xor_swap(a, b, rows=None):
    if rows == None and a.ndim == 2:
        rows = np.arange(len(a))
    
    a[rows, :] ^= b[rows, :]
    b[rows, :] ^= a[rows, :]
    a[rows, :] ^= b[rows, :] 

In [7]:
a = np.array([5, 6])
b = np.array([9, 8])

print(a)
print(b)

print('xor_swap')
xor_swap(a, b)

print(a)
print(b)

[5 6]
[9 8]
xor_swap
[9 8]
[5 6]


In [8]:
a = np.array([[5, 6], [7, 8]])
b = np.array([[1, 2], [3, 4]])

print('a:\n', a)
print('b:\n', b)

print('\nxor_swap')
xor_swap(a, b, rows=[1])

print('a:\n', a)
print('b:\n', b)

a:
 [[5 6]
 [7 8]]
b:
 [[1 2]
 [3 4]]

xor_swap
a:
 [[5 6]
 [3 4]]
b:
 [[1 2]
 [7 8]]
