In [1]:
import numpy as np

## 1. Warm up

In [2]:
a = np.zeros(3)
print(a.shape)
print(a.T.shape)
print(a[:, None].shape)
print(a[0])

(3,)
(3,)
(3, 1)
0.0


In [3]:
b = np.zeros(3,)
print(b.shape)
print(b.T.shape)
print(b[:, None].shape)
print(b[0])

(3,)
(3,)
(3, 1)
0.0


In [4]:
c = np.zeros((3, 1))
print(c.shape)
print(c.T.shape)
print(c[0])

(3, 1)
(1, 3)
[0.]


In [5]:
d = np.zeros((1, 3))
print(d.shape)
print(d.T.shape)
print(d[0])

(1, 3)
(3, 1)
[0. 0. 0.]


## 2. Play

In [6]:
# 1st test
w = np.arange(30).reshape(3, 10)
x = np.ones(10)
y = np.dot(w, x)

print(f'w:\n{w}')
print(f'x:\n{x}')
print(f'y:\n{y}')
print()

print(f'w.shape: {w.shape}')
print(f'x.shape: {x.shape}')
print(f'y.shape: {y.shape}')

w:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
x:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
y:
[ 45. 145. 245.]

w.shape: (3, 10)
x.shape: (10,)
y.shape: (3,)


In [7]:
# 2nd test
x = np.ones(3)
w = np.arange(30).reshape(3, 10)
y = np.dot(x, w)

print(f'x:\n{x}')
print(f'w:\n{w}')
print(f'y:\n{y}')
print()

print(f'x.shape: {x.shape}')
print(f'w.shape: {w.shape}')
print(f'y.shape: {y.shape}')

x:
[1. 1. 1.]
w:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
y:
[30. 33. 36. 39. 42. 45. 48. 51. 54. 57.]

x.shape: (3,)
w.shape: (3, 10)
y.shape: (10,)
