In [1]:
import matplotlib.animation as animation
import matplotlib.pyplot as plt
import numpy as np
import skimage
import retro
import sys

%matplotlib inline

print(f'sys.version: {sys.version}')
print(f'skimage.version: {skimage.__version__}')
print(f'retro.version: {retro.__version__}')

sys.version: 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
[GCC 7.3.0]
skimage.version: 0.14.1
retro.version: 0.6.1.dev25+g9ec2e44


In [2]:
env = retro.make('SpaceInvaders-Atari2600')

In [3]:
print(dir(env))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'action_space', 'action_to_array', 'auto_record', 'button_combos', 'buttons', 'close', 'compute_step', 'data', 'em', 'gamename', 'get_action_meaning', 'get_screen', 'img', 'initial_state', 'load_state', 'metadata', 'movie', 'movie_id', 'movie_path', 'np_random', 'num_buttons', 'observation_space', 'players', 'record_movie', 'render', 'reset', 'reward_range', 'seed', 'spec', 'statename', 'step', 'stop_record', 'system', 'unwrapped', 'use_restricted_actions', 'viewer']


In [4]:
s = env.reset()
a = env.action_space.sample()
print(a)
print(env.get_action_meaning(a))

[0 1 1 0 1 1 1 1]
[]


In [5]:
actions = np.identity(8, dtype=int)
for a in actions:
    print(a, ': ', env.get_action_meaning(a))

[1 0 0 0 0 0 0 0] :  ['BUTTON']
[0 1 0 0 0 0 0 0] :  []
[0 0 1 0 0 0 0 0] :  []
[0 0 0 1 0 0 0 0] :  []
[0 0 0 0 1 0 0 0] :  ['UP']
[0 0 0 0 0 1 0 0] :  ['DOWN']
[0 0 0 0 0 0 1 0] :  ['LEFT']
[0 0 0 0 0 0 0 1] :  ['RIGHT']


In [6]:
a = actions[7]
s = env.reset()
env.render()
done = False
step = 0

while not done:
    s, r, done, _ = env.step(a)
    step += 1
    if step % 100 == 0:
        a = actions[6 + (step // 100) % 2]
    env.render()
    
env.close()